// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var packet = packet || {};

/**
 * @enum
 */
packet.SrcDstType = {
  MATCHING_SERVER: 0,
  MATCHING_CLIENT: 1,
  ROOM_MANAGER: 2,
  PACKET_GENERATOR: 3,
  MONITORING_SERVER: 4,
  CONFIG_SERVER: 5,
  CONNECTION_SERVER: 6
};

/**
 * @enum
 */
packet.Command = {
  MATCH_REQUEST: 0,
  MATCH_COMPLET: 1,
  LATENCY: 2,
  HEALTH_CHECK: 3,
  MSLIST_REQUEST: 4,
  PG_START: 5,
  PG_END: 6
};

/**
 * @constructor
 */
packet.Header = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {packet.Header}
 */
packet.Header.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {packet.Header=} obj
 * @returns {packet.Header}
 */
packet.Header.getRootAsHeader = function(bb, obj) {
  return (obj || new packet.Header).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
packet.Header.prototype.length = function() {
  var offset = this.bb.__offset(this.bb_pos, 0);
  //return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;

    return this.bb.readInt32(0);
};

/**
 * @returns {packet.SrcDstType}
 */
packet.Header.prototype.srcType = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  //return offset ? /** @type {packet.SrcDstType} */ (this.bb.readInt32(this.bb_pos + offset)) : packet.SrcDstType.MATCHING_SERVER;
    return this.bb.readInt32(4);
};

/**
 * @returns {number}
 */
packet.Header.prototype.srcCode = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  //return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    return this.bb.readInt32(8);
};

/**
 * @returns {packet.SrcDstType}
 */
packet.Header.prototype.dstType = function() {
    var offset = this.bb.__offset(this.bb_pos, 10);
    //console.log('시발 오프셋:' + offset);
    //console.log('시발 bb_poost' + this.bb_pos);
    //console.log(this.bb.readInt32(this.bb_pos + 12));
  //return offset ? /** @type {packet.SrcDstType} */ (this.bb.readInt32(this.bb_pos + offset)) : packet.SrcDstType.MATCHING_SERVER;
    //console.log(this.bb.readInt32(this.bb_pos + 12));
    return this.bb.readInt32(12);
};

/**
 * @returns {number}
 */
packet.Header.prototype.dstCode = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  //return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    return this.bb.readInt32(16);
};

/**
 * @param {flatbuffers.Builder} builder
 */
packet.Header.startHeader = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} length
 */
packet.Header.addLength = function(builder, length) {
  builder.addFieldInt32(0, length, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {packet.SrcDstType} srcType
 */
packet.Header.addSrcType = function(builder, srcType) {
  builder.addFieldInt32(1, srcType, packet.SrcDstType.MATCHING_SERVER);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} srcCode
 */
packet.Header.addSrcCode = function(builder, srcCode) {
  builder.addFieldInt32(2, srcCode, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {packet.SrcDstType} dstType
 */
packet.Header.addDstType = function(builder, dstType) {
  builder.addFieldInt32(3, dstType, packet.SrcDstType.MATCHING_SERVER);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} dstCode
 */
packet.Header.addDstCode = function(builder, dstCode) {
  builder.addFieldInt32(4, dstCode, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
packet.Header.endHeader = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
packet.Body = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {packet.Body}
 */
packet.Body.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {packet.Body=} obj
 * @returns {packet.Body}
 */
packet.Body.getRootAsBody = function(bb, obj) {
  return (obj || new packet.Body).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {packet.Command}
 */
packet.Body.prototype.cmd = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {packet.Command} */ (this.bb.readInt32(this.bb_pos + offset)) : packet.Command.MATCH_REQUEST;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array}
 */
packet.Body.prototype.data = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
packet.Body.startBody = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {packet.Command} cmd
 */
packet.Body.addCmd = function(builder, cmd) {
  builder.addFieldInt32(0, cmd, packet.Command.MATCH_REQUEST);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
packet.Body.addData = function(builder, dataOffset) {
  builder.addFieldOffset(1, dataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
packet.Body.endBody = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.packet = packet;
